// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnluzhfqpxojbntwqtzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRubHV6aGZxcHhvamJudHdxdHp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NDQ4NDksImV4cCI6MjA2OTUyMDg0OX0.NbWdhgC33B8hryUmzLWAeRStPLR0QeCcDJdG0gEebi4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});